spring:
  application:
    name: service-customer-product
  data:
    mongodb:
      database: bootcamp_customer_product_db
      host: localhost
      port: 8092
  config:
    import: optional:configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8002
message:
  path-customerProductPassive: /api/v1/customerProductsPassive
  path-customerProductActive: /api/v1/customerProductsActive