spring:
  application:
    name: service-product
  data:
    mongodb:
      database: bootcamp_product_db
      host: localhost
      port: 27018
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productTypes
  uri: /api/v1/productTypes/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/