spring:
  application:
    name: service-customer
  data:
    mongodb:
      database: bootcamp_customer_db
      host: db_customer
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8000
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerTypes
  uri: /api/v1/customerTypes/
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.220:8000/eureka/