spring:
  application:
    name: ms-product
  data:
    mongodb:
      database: bootcamp_product_db
      host: db_product
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8000
message:
  path-product: /api/v1/products
  path-productType: /api/v1/productTypes
  uri: /api/v1/productTypes/