spring:
  application:
    name: service-operation
  data:
    mongodb:
      database: bootcamp_operation_db
      host: localhost
      port: 27020
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8084
message:
  path-operation: /api/v1/operations
  path-operationType: /api/v1/operationTypes
  uri: /api/v1/operationTypes
  uri2: /api/v1/customerProductsPassive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/