spring:
  application:
    name: ms-customer-product
  data:
    mongodb:
      database: bootcamp_customer_product_db
      host: db_customer_product
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8000
message:
  path-customerProductPassive: /api/v1/customerProductsPassive
  path-customerProductActive: /api/v1/customerProductsActive
  uri: /api/v1/customers/
  uri2: /api/v1/products/