spring:
  application:
    name: service-payment
  data:
    mongodb:
      database: bootcamp_payment_db
      host: db_payment
      port: 27021
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 808
message:
  path-payment: /api/v1/payment
  uri: /api/v1/customerProductsActive/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/