spring:
  application:
    name: ms-shopping
  data:
    mongodb:
      database: bootcamp_shopping_db
      host: db_shopping
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8000
message:
  path-shopping: /api/v1/shoppings
  uri: /api/v1/customerTypes/