spring:
  application:
    name: service-shopping
  data:
    mongodb:
      database: bootcamp_shopping_db
      host: db_shopping
      port: 27022
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8086
message:
  path-shopping: /api/v1/shoppings
  uri: /api/v1/customerTypes/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/