spring:
  application:
    name: service-operation
  data:
    mongodb:
      database: bootcamp_operation_db
      host: db_operation
      port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8000
message:
  path-operation: /api/v1/operations
  path-operationType: /api/v1/operationTypes
  uri: /api/v1/operationTypes
  uri2: /api/v1/customerProductsPassive
eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.220:8000/eureka/